language: node_js
node_js:
- '12'

env:
  global:
  - NODE_ENV=production
  - MONGO_DB_NAME=whs
  - secure: cJGzeCJOY81QtKM/L98IQxppd8+AGJjpQNfEiZhmpEIlyw47/OKeHNWNR/xLEZb6FkPjN+mNL3M+j8aaT2h0MyeifFucDXvBHtZ/kyHHv4UyvGh8/ushKlAzjG4b91gML4BII7bXvU/45BuBN0UJv/sFn2jmSUI70v7szDylNmgka5E7LINfW9L3Lkuw1zoDRwUmDMYxdKfMSEX2kw2PJkQcnWo2KEEin1vaFzKUkZqmvn+Ey38TJ49SDVzeoPS0dejjEVVmuaGWz4zAlobdIlLURuDfoFRuMK45LwBbDXfe2aQXzp+0j//N/Oko0aUOp01VNbooD+grfyO1esnlj4Wjq5TLz0f1T8N/RDR/u9mYfpIQE3W68pWndluVmiTA85hdBwsRxJ2gOWuFl5LdXnpWUdWI6vMdLd2wa8v7CezuwtesiVYh2GPVNoLrmZ3eR5Vy5uF2hpcJeQuC759dSx6uew5FbIIysE1MJixi8JIEjwB8J5lk6Prb0CSnqqHkU+2iVeTyVlL9LLMNCxTLgVn6yof5eicxf9S1s3rARx0dm+4cxeyV6IiQwgxKMO7QxwSxx+N/SHej2BEozCZRZvur8aJT5Am6LgBLv2cU2TTyi/z9yTH6OiiKpUTET020+AyG658Ztbi9wWIvhPGaRUrTpe5t06hy9d3hj+43UrE=
  - secure: PDJq2qOqe2nDHI6PHj4LmhW9hQSvsVr0cReVGw6kmfPihDjqjRmK2vlmOrYRM/gqFj7j33aolVfKpUjz85MGuVB89gsAU8L9/aAD7cAa2smuuH82K72sabzsHwJj+SU6mouKe2jTJMiBnkUy7Ym3knK7ia1G/jvKMJ1uqqHFUB4f1WOSiYGa00D929qbkw4wpLncSAKLs/edDehljBJdaOP524jETjlJUf16l3cuaYpRuj9OOafUhccZKssRqtdaHloUDI/fWUoRv9r8U9g1GmmJ8airxncPncpsypVDmYOVa8kqUblPABfRLiIpb82nus+LkU2ChvskGfknncBZXvCD7YvGBfRdHuL3FaxPLnGByLUt5+t+q+mkKuZ0F9bC8wva1OUSeFItchj/JF7Vq+xO8ax9aCx0bxUk6rZ5E17yBOSVVnUPneHxu5x9UHy7qqjKKIcMmdSS7OhiPD0UW0DokJSRmszc7HpdvTU8gKsZFfQUfKI8UAooSdkcgMpSiJbXyinQ+zXp+DFJSw2slhkPgZXewiDzTP3z+cqiDi5p6jYE5t5+K1a9sBLVWOJ/Pd84+iUXZcC1q37omHYATmqHmec6byKCYs+r4V+YuDtZdCvGvG4FYp4OPi5CyCWJ6S/YLewdqgLwQi4qe1ygfiv16PoyRQHecoJxg6o1pwc=

cache:
  directories:
  - './packages/server/node_modules/.cache/mongodb-memory-server/mongodb-binaries'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add lerna coveralls
install: yarn && lerna bootstrap

jobs:
  include:
    - stage: Test
      name: App Unit Tests
      node_js: node
      script: yarn workspace @whs/app test:coverage | coveralls
    - script: yarn workspace @whs/server test:coverage | coveralls
      name: Server Unit Tests
      node_js: node
